import {
  isLandEquipmentSidc,
  resolveLandEquipmentCategoryFromSidc,
  resolveLandEquipmentSubcategoryFromSidc,
} from "./index";
import {
  findBestOverrideRow,
  type LandEquipShapeOverride,
  type TokenMap,
} from "./landEquipmentRecipeEngine";

export const SHAPE_GRAMMAR_TOKENS: TokenMap = {
  veh_small: "5.5x2.8x2.6",
  veh_medium: "6.5x3.5x3.0",
  veh_long: "8.5x3.5x3.2",
  rail_car: "13.5x3.2x3.8",
  trailer_long: "10.5x3.5x3.2",
  wheel_small: "r=0.42,h=1.0",
  wheel_medium: "r=0.5,h=1.2",
  wheel_large: "r=0.6,h=1.3",
  tube_small: "r=0.35,h=4.5",
  tube_medium: "r=0.45,h=5.0",
  tube_large: "r=0.65,h=5.0",
  mast_small: "r=0.22,h=2.8",
  mast_medium: "r=0.28,h=3.6",
  dome_small: "r=0.55,h=0.55",
  mine_small: "0.65x0.65x0.22",
  mine_large: "0.9x0.9x0.28",
  crate_small: "1.2x1.2x1.0",
  crate_medium: "1.8x1.4x1.2",
};

export const LAND_EQUIP_SHAPE_OVERRIDES: LandEquipShapeOverride[] = [
  // 13 Engineer Vehicles and Equipment
  {
    entityCode: "13",
    entityTypeCode: "01",
    entitySubtypeCode: "*",
    proposedShapeType: "engBridge",
    primitiveRecipe: "box(veh_long) + 4x cylinder(wheel_medium,offset=corners,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "med",
    priority: "P1",
    notes: "Bridge section carrier silhouette.",
  },
  {
    entityCode: "13",
    entityTypeCode: "09",
    entitySubtypeCode: "*",
    proposedShapeType: "engMineClearing",
    primitiveRecipe: "box(veh_medium) + cylinder(tube_large,offset=front,axis=longitudinal) + 4x cylinder(wheel_medium,offset=corners,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "med",
    priority: "P1",
    notes: "Front-mounted drum proxy.",
  },
  {
    entityCode: "13",
    entityTypeCode: "*",
    entitySubtypeCode: "*",
    proposedShapeType: "engVehicleGeneric",
    primitiveRecipe: "box(veh_medium)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Category fallback.",
  },

  // 14 Utility Vehicles
  {
    entityCode: "14",
    entityTypeCode: "02",
    entitySubtypeCode: "*",
    proposedShapeType: "utilityMedical",
    primitiveRecipe: "box(veh_medium) + 4x cylinder(wheel_medium,offset=corners,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Medical truck profile.",
  },
  {
    entityCode: "14",
    entityTypeCode: "05",
    entitySubtypeCode: "*",
    proposedShapeType: "utilityBus",
    primitiveRecipe: "box(veh_long)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Bus silhouette.",
  },
  {
    entityCode: "14",
    entityTypeCode: "06",
    entitySubtypeCode: "01",
    proposedShapeType: "utilitySemiTrailerLight",
    primitiveRecipe: "box(veh_medium)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Light semi-trailer profile.",
  },
  {
    entityCode: "14",
    entityTypeCode: "06",
    entitySubtypeCode: "02",
    proposedShapeType: "utilitySemiTrailerMedium",
    primitiveRecipe: "box(veh_long)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Medium semi-trailer profile.",
  },
  {
    entityCode: "14",
    entityTypeCode: "06",
    entitySubtypeCode: "03",
    proposedShapeType: "utilitySemiTrailerHeavy",
    primitiveRecipe: "box(trailer_long)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Heavy semi-trailer profile.",
  },
  {
    entityCode: "14",
    entityTypeCode: "06",
    entitySubtypeCode: "*",
    proposedShapeType: "utilitySemiTrailer",
    primitiveRecipe: "box(trailer_long)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Semi-trailer and truck family.",
  },
  {
    entityCode: "14",
    entityTypeCode: "12",
    entitySubtypeCode: "01",
    proposedShapeType: "utilityTowTruckLight",
    primitiveRecipe: "box(veh_medium) + cylinder(mast_small,offset=rear-top,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "med",
    priority: "P1",
    notes: "Light tow truck profile.",
  },
  {
    entityCode: "14",
    entityTypeCode: "12",
    entitySubtypeCode: "02",
    proposedShapeType: "utilityTowTruckHeavy",
    primitiveRecipe: "box(veh_long) + cylinder(mast_medium,offset=rear-top,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "med",
    priority: "P1",
    notes: "Heavy tow truck profile.",
  },
  {
    entityCode: "14",
    entityTypeCode: "12",
    entitySubtypeCode: "*",
    proposedShapeType: "utilityTowTruck",
    primitiveRecipe: "box(veh_medium) + cylinder(mast_small,offset=rear-top,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "med",
    priority: "P1",
    notes: "Rear boom proxy.",
  },
  {
    entityCode: "14",
    entityTypeCode: "*",
    entitySubtypeCode: "*",
    proposedShapeType: "utilityVehicleGeneric",
    primitiveRecipe: "box(veh_medium)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Category fallback.",
  },

  // 15 Trains
  {
    entityCode: "15",
    entityTypeCode: "01",
    entitySubtypeCode: "*",
    proposedShapeType: "trainLocomotive",
    primitiveRecipe: "box(rail_car) + 4x cylinder(wheel_large,offset=bogies,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Locomotive proxy.",
  },
  {
    entityCode: "15",
    entityTypeCode: "02",
    entitySubtypeCode: "*",
    proposedShapeType: "trainRailcar",
    primitiveRecipe: "box(rail_car) + 4x cylinder(wheel_large,offset=bogies,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Railcar proxy.",
  },
  {
    entityCode: "15",
    entityTypeCode: "*",
    entitySubtypeCode: "*",
    proposedShapeType: "trainGeneric",
    primitiveRecipe: "box(rail_car) + 4x cylinder(wheel_large,offset=bogies,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P2",
    notes: "Category fallback.",
  },

  // 16 Civilian Vehicles
  {
    entityCode: "16",
    entityTypeCode: "01",
    entitySubtypeCode: "01",
    proposedShapeType: "civilianAutomobileCompact",
    primitiveRecipe: "box(5.0x2.4x2.2)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Compact car profile.",
  },
  {
    entityCode: "16",
    entityTypeCode: "01",
    entitySubtypeCode: "02",
    proposedShapeType: "civilianAutomobileMidsize",
    primitiveRecipe: "box(5.5x2.6x2.4)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Midsize car profile.",
  },
  {
    entityCode: "16",
    entityTypeCode: "01",
    entitySubtypeCode: "03",
    proposedShapeType: "civilianAutomobileSedan",
    primitiveRecipe: "box(5.8x2.8x2.5)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Sedan profile.",
  },
  {
    entityCode: "16",
    entityTypeCode: "01",
    entitySubtypeCode: "*",
    proposedShapeType: "civilianAutomobile",
    primitiveRecipe: "box(veh_small)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Sedan/compact family fallback.",
  },
  {
    entityCode: "16",
    entityTypeCode: "03",
    entitySubtypeCode: "*",
    proposedShapeType: "civilianPassengerVehicle",
    primitiveRecipe: "box(veh_medium)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Van/bus family.",
  },
  {
    entityCode: "16",
    entityTypeCode: "06",
    entitySubtypeCode: "01",
    proposedShapeType: "civilianTractorTrailerSmall",
    primitiveRecipe: "box(veh_long)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Small/light tractor trailer.",
  },
  {
    entityCode: "16",
    entityTypeCode: "06",
    entitySubtypeCode: "02",
    proposedShapeType: "civilianTractorTrailerMedium",
    primitiveRecipe: "box(trailer_long)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Medium tractor trailer.",
  },
  {
    entityCode: "16",
    entityTypeCode: "06",
    entitySubtypeCode: "03",
    proposedShapeType: "civilianTractorTrailerLarge",
    primitiveRecipe: "box(11.5x3.8x3.5)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Large/heavy tractor trailer.",
  },
  {
    entityCode: "16",
    entityTypeCode: "06",
    entitySubtypeCode: "*",
    proposedShapeType: "civilianTractorTrailer",
    primitiveRecipe: "box(trailer_long)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Truck with box trailer.",
  },
  {
    entityCode: "16",
    entityTypeCode: "07",
    entitySubtypeCode: "*",
    proposedShapeType: "civilianFlatbedTrailer",
    primitiveRecipe: "box(trailer_long)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Flatbed trailer proxy.",
  },
  {
    entityCode: "16",
    entityTypeCode: "*",
    entitySubtypeCode: "*",
    proposedShapeType: "civilianVehicleGeneric",
    primitiveRecipe: "box(veh_small)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Category fallback.",
  },

  // 17 Law Enforcement
  {
    entityCode: "17",
    entityTypeCode: "*",
    entitySubtypeCode: "*",
    proposedShapeType: "lawVehicleGeneric",
    primitiveRecipe: "box(veh_small)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Ground vehicle proxy for agency-specific icons.",
  },

  // 19 Missile Support
  {
    entityCode: "19",
    entityTypeCode: "01",
    entitySubtypeCode: "*",
    proposedShapeType: "missileSupportTransloader",
    primitiveRecipe: "box(veh_long) + box(crate_small,offset=rear-top) + 6x cylinder(wheel_medium,offset=3axles,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "med",
    priority: "P1",
    notes: "Rear loading area proxy.",
  },
  {
    entityCode: "19",
    entityTypeCode: "02",
    entitySubtypeCode: "*",
    proposedShapeType: "missileSupportTransporter",
    primitiveRecipe: "box(veh_long) + 6x cylinder(wheel_medium,offset=3axles,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Long transporter body.",
  },
  {
    entityCode: "19",
    entityTypeCode: "03",
    entitySubtypeCode: "*",
    proposedShapeType: "missileSupportCrane",
    primitiveRecipe: "box(veh_medium) + cylinder(mast_medium,offset=rear-top,axis=longitudinal) + 4x cylinder(wheel_medium,offset=corners,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "med",
    priority: "P1",
    notes: "Crane/loading silhouette.",
  },
  {
    entityCode: "19",
    entityTypeCode: "*",
    entitySubtypeCode: "*",
    proposedShapeType: "missileSupportGeneric",
    primitiveRecipe: "box(veh_long) + 6x cylinder(wheel_medium,offset=3axles,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Transporter/transloader fallback.",
  },

  // 20 Other Equipment
  {
    entityCode: "20",
    entityTypeCode: "02",
    entitySubtypeCode: "*",
    proposedShapeType: "otherBomb",
    primitiveRecipe: "sphere(r=0.6)",
    orientationAssumption: "n/a",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P2",
    notes: "Simple bomb marker.",
  },
  {
    entityCode: "20",
    entityTypeCode: "03",
    entitySubtypeCode: "*",
    proposedShapeType: "otherBoobyTrap",
    primitiveRecipe: "box(crate_small)",
    orientationAssumption: "n/a",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "med",
    priority: "P2",
    notes: "Booby trap placeholder.",
  },
  {
    entityCode: "20",
    entityTypeCode: "13",
    entitySubtypeCode: "*",
    proposedShapeType: "otherTent",
    primitiveRecipe: "triangularPrism(4.5x4.0x2.2)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "med",
    priority: "P2",
    notes: "Rendered as box fallback in current Cesium entity path.",
  },
  {
    entityCode: "20",
    entityTypeCode: "01",
    entitySubtypeCode: "*",
    proposedShapeType: "otherAntennae",
    primitiveRecipe: "cylinder(mast_medium) + sphere(dome_small,offset=top)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "med",
    priority: "P2",
    notes: "Mast + dome proxy.",
  },
  {
    entityCode: "20",
    entityTypeCode: "*",
    entitySubtypeCode: "*",
    proposedShapeType: "otherEquipmentGeneric",
    primitiveRecipe: "box(crate_medium)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P2",
    notes: "Safe placeholder for abstract equipment.",
  },

  // 21 Land Mines
  {
    entityCode: "21",
    entityTypeCode: "04",
    entitySubtypeCode: "*",
    proposedShapeType: "landMineIed",
    primitiveRecipe: "box(crate_small)",
    orientationAssumption: "n/a",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P2",
    notes: "IED marker using low-profile crate form.",
  },
  {
    entityCode: "21",
    entityTypeCode: "01",
    entitySubtypeCode: "*",
    proposedShapeType: "landMineGeneral",
    primitiveRecipe: "box(mine_small)",
    orientationAssumption: "n/a",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P2",
    notes: "Low-profile marker.",
  },
  {
    entityCode: "21",
    entityTypeCode: "03",
    entitySubtypeCode: "*",
    proposedShapeType: "landMineAntitank",
    primitiveRecipe: "box(mine_large)",
    orientationAssumption: "n/a",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P2",
    notes: "Larger low-profile marker.",
  },
  {
    entityCode: "21",
    entityTypeCode: "*",
    entitySubtypeCode: "*",
    proposedShapeType: "landMineFallback",
    primitiveRecipe: "box(mine_small)",
    orientationAssumption: "n/a",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P2",
    notes: "Category fallback.",
  },

  // 22 Sensors
  {
    entityCode: "22",
    entityTypeCode: "01",
    entitySubtypeCode: "*",
    proposedShapeType: "sensorGeneric",
    primitiveRecipe: "cylinder(mast_small) + sphere(dome_small,offset=top)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Pole + head silhouette.",
  },
  {
    entityCode: "22",
    entityTypeCode: "02",
    entitySubtypeCode: "*",
    proposedShapeType: "sensorEmplaced",
    primitiveRecipe: "box(crate_small) + cylinder(mast_small,offset=top)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Emplaced sensor on short base.",
  },
  {
    entityCode: "22",
    entityTypeCode: "03",
    entitySubtypeCode: "*",
    proposedShapeType: "sensorRadar",
    primitiveRecipe: "box(crate_small) + cylinder(mast_small,offset=top) + sphere(dome_small,offset=top-front)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "med",
    priority: "P1",
    notes: "Simple radar proxy.",
  },
  {
    entityCode: "22",
    entityTypeCode: "*",
    entitySubtypeCode: "*",
    proposedShapeType: "sensorFallback",
    primitiveRecipe: "cylinder(mast_small)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P2",
    notes: "Category fallback.",
  },

  // 23 Emergency Operation
  {
    entityCode: "23",
    entityTypeCode: "01",
    entitySubtypeCode: "*",
    proposedShapeType: "emergencyAmbulance",
    primitiveRecipe: "box(veh_medium)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Ambulance profile.",
  },
  {
    entityCode: "23",
    entityTypeCode: "02",
    entitySubtypeCode: "*",
    proposedShapeType: "emergencyFire",
    primitiveRecipe: "box(veh_long) + cylinder(mast_small,offset=top-rear,axis=longitudinal)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P1",
    notes: "Fire apparatus proxy.",
  },
  {
    entityCode: "23",
    entityTypeCode: "*",
    entitySubtypeCode: "*",
    proposedShapeType: "emergencyGeneric",
    primitiveRecipe: "box(veh_medium)",
    orientationAssumption: "forward=north",
    anchorAltitude: "ground-hugging-center",
    labelOffset: [-3, 0, 3],
    removeLegacySidcPedestal: true,
    confidence: "high",
    priority: "P2",
    notes: "Category fallback.",
  },
];

const sidcOverrideMemo = new Map<string, LandEquipShapeOverride | null>();

export function findLandEquipShapeOverrideForSidc(sidc?: string): LandEquipShapeOverride | undefined {
  if (typeof sidc !== "string") return undefined;
  const normalized = sidc.trim();
  if (!normalized) return undefined;
  const cached = sidcOverrideMemo.get(normalized);
  if (cached !== undefined) return cached ?? undefined;
  if (!isLandEquipmentSidc(normalized)) {
    sidcOverrideMemo.set(normalized, null);
    return undefined;
  }
  const category = resolveLandEquipmentCategoryFromSidc(normalized);
  const subcategory = resolveLandEquipmentSubcategoryFromSidc(normalized);
  const entityCode = subcategory?.entityCode ?? category?.entityCode;
  const entityTypeCode = subcategory?.entityTypeCode;
  const entitySubtypeCode = subcategory?.entitySubtypeCode;
  if (!entityCode || !entityTypeCode) {
    sidcOverrideMemo.set(normalized, null);
    return undefined;
  }
  const row = findBestOverrideRow(
    LAND_EQUIP_SHAPE_OVERRIDES,
    String(entityCode),
    String(entityTypeCode),
    entitySubtypeCode != null ? String(entitySubtypeCode) : "*",
  );
  sidcOverrideMemo.set(normalized, row ?? null);
  return row;
}

export function hasLandEquipRecipeOverrideForSidc(sidc?: string): boolean {
  return !!findLandEquipShapeOverrideForSidc(sidc);
}
