import type { LandEquipmentSubcategoryDefinition } from "../types";

export const ENGINEER_VEHICLES_AND_EQUIPMENT_SUBCATEGORY_DEFINITIONS: LandEquipmentSubcategoryDefinition[] =
  [
    { id: "engineer-bridge", name: "Bridge", symbolSet: "15", entityCode: "13", entityTypeCode: "01" },
    {
      id: "engineer-bridge-mounted-on-utility-vehicle",
      name: "Bridge Mounted on Utility Vehicle",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "02",
    },
    { id: "engineer-fixed-bridge", name: "Fixed Bridge", symbolSet: "15", entityCode: "13", entityTypeCode: "03" },
    {
      id: "engineer-floating-bridge",
      name: "Floating Bridge",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "04",
    },
    {
      id: "engineer-folding-girder-bridge",
      name: "Folding Girder Bridge",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "05",
    },
    {
      id: "engineer-hollow-deck-bridge",
      name: "Hollow Deck Bridge",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "06",
    },
    { id: "engineer-drill", name: "Drill", symbolSet: "15", entityCode: "13", entityTypeCode: "07" },
    {
      id: "engineer-drill-mounted-on-utility-vehicle",
      name: "Drill Mounted on Utility Vehicle",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "07",
      entitySubtypeCode: "01",
    },
    {
      id: "engineer-earthmover",
      name: "Earthmover",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "08",
    },
    {
      id: "engineer-earthmover-multifunctional-digger",
      name: "Multifunctional Earthmover/Digger",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "08",
      entitySubtypeCode: "01",
    },
    {
      id: "engineer-mine-clearing-equipment",
      name: "Mine Clearing Equipment",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "09",
    },
    {
      id: "engineer-mine-clearing-trailer-mounted",
      name: "Mine Clearing Equipment Trailer Mounted",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "09",
      entitySubtypeCode: "01",
    },
    {
      id: "engineer-mine-clearing-tank-chassis",
      name: "Mine Clearing Equipment on Tank Chassis",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "09",
      entitySubtypeCode: "02",
    },
    {
      id: "engineer-assault-breacher-vehicle",
      name: "Assault Breacher Vehicle (ABV) with Combat Dozer Blade",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "09",
      entitySubtypeCode: "03",
    },
    {
      id: "engineer-mine-clearing-medium-capability",
      name: "Mine Clearing Equipment Medium Capability",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "09",
      entitySubtypeCode: "04",
    },
    {
      id: "engineer-mine-clearing-heavy-capability",
      name: "Mine Clearing Equipment Heavy Capability",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "09",
      entitySubtypeCode: "05",
    },
    {
      id: "engineer-mine-laying-equipment",
      name: "Mine Laying Equipment",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "10",
    },
    {
      id: "engineer-mine-laying-on-utility-vehicle",
      name: "Mine Laying Equipment on Utility Vehicle",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "10",
      entitySubtypeCode: "01",
    },
    {
      id: "engineer-mine-laying-armored-carrier-volcano",
      name: "Mine Laying Equipment Armored Carrier with Volcano",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "10",
      entitySubtypeCode: "02",
    },
    {
      id: "engineer-mine-laying-truck-mounted-volcano",
      name: "Mine Laying Equipment Truck Mounted with Volcano",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "10",
      entitySubtypeCode: "03",
    },
    { id: "engineer-dozer", name: "Dozer", symbolSet: "15", entityCode: "13", entityTypeCode: "11" },
    {
      id: "engineer-dozer-armored",
      name: "Dozer, Armored",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "11",
      entitySubtypeCode: "01",
    },
    {
      id: "engineer-armored-assault",
      name: "Armored Assault",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "12",
    },
    {
      id: "engineer-aerv",
      name: "Armored Engineer Recon Vehicle (AERV)",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "13",
    },
    { id: "engineer-backhoe", name: "Backhoe", symbolSet: "15", entityCode: "13", entityTypeCode: "14" },
    {
      id: "engineer-construction-vehicle",
      name: "Construction Vehicle",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "15",
    },
    {
      id: "engineer-ferry-transporter",
      name: "Ferry Transporter",
      symbolSet: "15",
      entityCode: "13",
      entityTypeCode: "16",
    },
  ];
