import type { LandEquipmentSubcategoryDefinition } from "../types";

export const OTHER_EQUIPMENT_SUBCATEGORY_DEFINITIONS: LandEquipmentSubcategoryDefinition[] = [
  { id: "other-equipment-antennae", name: "Antennae", symbolSet: "15", entityCode: "20", entityTypeCode: "01" },
  { id: "other-equipment-bomb", name: "Bomb", symbolSet: "15", entityCode: "20", entityTypeCode: "02" },
  { id: "other-equipment-booby-trap", name: "Booby Trap", symbolSet: "15", entityCode: "20", entityTypeCode: "03" },
  { id: "other-equipment-cbrn", name: "CBRN Equipment", symbolSet: "15", entityCode: "20", entityTypeCode: "04" },
  { id: "other-equipment-computer-system", name: "Computer System", symbolSet: "15", entityCode: "20", entityTypeCode: "05" },
  {
    id: "other-equipment-command-launch-equipment",
    name: "Command Launch Equipment (CLE)",
    symbolSet: "15",
    entityCode: "20",
    entityTypeCode: "06",
  },
  { id: "other-equipment-generator-set", name: "Generator Set", symbolSet: "15", entityCode: "20", entityTypeCode: "07" },
  {
    id: "other-equipment-gmd-fire-control-center",
    name: "Ground-based Midcourse Defense (GMD) Fire Control (GFC) Center",
    symbolSet: "15",
    entityCode: "20",
    entityTypeCode: "08",
  },
  {
    id: "other-equipment-ifics-data-terminal",
    name: "In-Flight Interceptor Communications System (IFICS) Data Terminal (IDT)",
    symbolSet: "15",
    entityCode: "20",
    entityTypeCode: "09",
  },
  { id: "other-equipment-laser", name: "Laser", symbolSet: "15", entityCode: "20", entityTypeCode: "10" },
  {
    id: "other-equipment-miso",
    name: "Military Information Support Operations (MISO)",
    symbolSet: "15",
    entityCode: "20",
    entityTypeCode: "11",
  },
  { id: "other-equipment-sustainment-shipments", name: "Sustainment Shipments", symbolSet: "15", entityCode: "20", entityTypeCode: "12" },
  { id: "other-equipment-tent", name: "Tent", symbolSet: "15", entityCode: "20", entityTypeCode: "13" },
  { id: "other-equipment-tent-civilian", name: "Tent Civilian", symbolSet: "15", entityCode: "20", entityTypeCode: "13", entitySubtypeCode: "01" },
  { id: "other-equipment-tent-military", name: "Tent Military", symbolSet: "15", entityCode: "20", entityTypeCode: "13", entitySubtypeCode: "02" },
  {
    id: "other-equipment-unit-deployment-shipments",
    name: "Unit Deployment Shipments",
    symbolSet: "15",
    entityCode: "20",
    entityTypeCode: "14",
  },
  {
    id: "other-equipment-emergency-medical-operation",
    name: "Emergency Medical Operation",
    symbolSet: "15",
    entityCode: "20",
    entityTypeCode: "15",
  },
  {
    id: "other-equipment-medical-evacuation-helicopter",
    name: "Emergency Medical Operation Medical Evacuation Helicopter",
    symbolSet: "15",
    entityCode: "20",
    entityTypeCode: "15",
    entitySubtypeCode: "01",
  },
];
