import type { LandEquipmentSubcategoryDefinition } from "../types";

export const VEHICLES_SUBCATEGORY_DEFINITIONS: LandEquipmentSubcategoryDefinition[] = [
  // Type-level fallbacks
  { id: "vehicle-armored", name: "Armored", symbolSet: "15", entityCode: "12", entityTypeCode: "01" },
  { id: "vehicle-tank", name: "Tank", symbolSet: "15", entityCode: "12", entityTypeCode: "02" },
  {
    id: "vehicle-tank-recovery",
    name: "Tank Recovery Vehicle",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "03",
  },

  // Armored subtypes (1201xx)
  {
    id: "vehicle-armored-fighting",
    name: "Armored Fighting Vehicle",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "01",
    entitySubtypeCode: "01",
  },
  {
    id: "vehicle-armored-c2",
    name: "Armored Fighting Vehicle Command and Control",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "01",
    entitySubtypeCode: "02",
  },
  {
    id: "vehicle-apc",
    name: "Armored Personnel Carrier",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "01",
    entitySubtypeCode: "03",
  },
  {
    id: "vehicle-apc-ambulance",
    name: "Armored Personnel Carrier Ambulance",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "01",
    entitySubtypeCode: "04",
  },
  {
    id: "vehicle-protected",
    name: "Armored Protected Vehicle",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "01",
    entitySubtypeCode: "05",
  },
  {
    id: "vehicle-protected-recovery",
    name: "Armored Protected Vehicle Recovery",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "01",
    entitySubtypeCode: "06",
  },
  {
    id: "vehicle-protected-med-evac",
    name: "Armored Protected Vehicle Medical Evacuation",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "01",
    entitySubtypeCode: "07",
  },
  {
    id: "vehicle-apc-recovery",
    name: "Armored Personnel Carrier, Recovery",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "01",
    entitySubtypeCode: "08",
  },
  {
    id: "vehicle-combat-service-support",
    name: "Combat Service Support Vehicle",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "01",
    entitySubtypeCode: "09",
  },
  {
    id: "vehicle-light-wheeled-armored",
    name: "Light Wheeled Armored Vehicle",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "01",
    entitySubtypeCode: "10",
  },
  {
    id: "vehicle-light-armor-recon",
    name: "Light Armor Reconnaissance",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "01",
    entitySubtypeCode: "11",
  },

  // Tank subtypes (1202xx)
  {
    id: "vehicle-tank-light",
    name: "Tank Light",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "02",
    entitySubtypeCode: "01",
  },
  {
    id: "vehicle-tank-medium",
    name: "Tank Medium",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "02",
    entitySubtypeCode: "02",
  },
  {
    id: "vehicle-tank-heavy",
    name: "Tank Heavy",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "02",
    entitySubtypeCode: "03",
  },

  // Tank recovery subtypes (1203xx)
  {
    id: "vehicle-tank-recovery-light",
    name: "Tank Recovery Vehicle Light",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "03",
    entitySubtypeCode: "01",
  },
  {
    id: "vehicle-tank-recovery-medium",
    name: "Tank Recovery Vehicle Medium",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "03",
    entitySubtypeCode: "02",
  },
  {
    id: "vehicle-tank-recovery-heavy",
    name: "Tank Recovery Vehicle Heavy",
    symbolSet: "15",
    entityCode: "12",
    entityTypeCode: "03",
    entitySubtypeCode: "03",
  },
];
