import type { LandEquipmentSubcategoryDefinition } from "../types";

export const WEAPONS_WEAPON_SYSTEM_SUBCATEGORY_DEFINITIONS: LandEquipmentSubcategoryDefinition[] = [
  { id: "weapon-rifle", name: "Rifle", symbolSet: "15", entityCode: "11", entityTypeCode: "01" },
  { id: "weapon-machine-gun", name: "Machine Gun", symbolSet: "15", entityCode: "11", entityTypeCode: "02" },
  {
    id: "weapon-grenade-launcher",
    name: "Grenade Launcher",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "03",
  },
  {
    id: "weapon-flame-thrower",
    name: "Flame Thrower",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "04",
  },
  {
    id: "weapon-air-defense-gun",
    name: "Air Defense Gun",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "05",
  },
  { id: "weapon-antitank-gun", name: "Antitank Gun", symbolSet: "15", entityCode: "11", entityTypeCode: "06" },
  {
    id: "weapon-direct-fire-gun",
    name: "Direct Fire Gun",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "07",
  },
  { id: "weapon-recoilless-gun", name: "Recoilless Gun", symbolSet: "15", entityCode: "11", entityTypeCode: "08" },
  { id: "weapon-howitzer", name: "Howitzer", symbolSet: "15", entityCode: "11", entityTypeCode: "09" },
  {
    id: "weapon-missile-launcher",
    name: "Missile Launcher",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "10",
  },
  {
    id: "weapon-air-defense-missile-launcher",
    name: "Air Defense Missile Launcher",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "11",
  },
  {
    id: "weapon-antitank-missile-launcher",
    name: "Antitank Missile Launcher",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "12",
  },
  {
    id: "weapon-surface-to-surface-missile-launcher",
    name: "Surface-to-Surface Missile Launcher",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "13",
  },
  { id: "weapon-mortar", name: "Mortar", symbolSet: "15", entityCode: "11", entityTypeCode: "14" },
  {
    id: "weapon-single-rocket-launcher",
    name: "Single Rocket Launcher",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "15",
  },
  {
    id: "weapon-multiple-rocket-launcher",
    name: "Multiple Rocket Launcher",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "16",
  },
  {
    id: "weapon-antitank-rocket-launcher",
    name: "Antitank Rocket Launcher",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "17",
  },
  {
    id: "weapon-nonlethal",
    name: "Nonlethal Weapon",
    symbolSet: "15",
    entityCode: "11",
    entityTypeCode: "18",
  },
  { id: "weapon-taser", name: "Taser", symbolSet: "15", entityCode: "11", entityTypeCode: "19" },
  { id: "weapon-water-cannon", name: "Water Cannon", symbolSet: "15", entityCode: "11", entityTypeCode: "20" },
];
